### ISSUE TITLE
Why "Reset static completions"?

### ISSUE THREAD

**Issue by HaleTom** [cykerway/complete-alias#1]
At:
https://github.com/cykerway/complete-alias/blob/master/completions/bash_completion.sh#L26
you reset a bunch of aliases.

I've read the comment, but can't really get what you're trying to do. What's an example of this being needed?

How do you know that those aliases haven't been changed by the user, and resetting them will not cause unexpected behaviour?

**Comment by cykerway** [comment]
Reset those aliases to prevent infinite recursion. For example, if `ls` is aliased to `ls -l`, then the `_complete_alias` function should only be used in the first completion and the default completion function for `ls` should be used afterwards. Otherwise you'd have `ls` expanded to `ls -l`, `ls -l -l`, etc.

Theoretically we should be able to store the original completion function for a command retrieved via `complete -p <cmd>` before we complete an alias and restore it after so. Practically my life fell into trouble and I never had time or money to finish this TODO. So if you think the current job is imperfect or incomplete then you're probably right. And I'd be very happy to finish the remaining job on this free software if I found free beef noodles on the street. For now, the default completions should work fine for most users. If you have special needs, for example if you use different a completion function for a command, then you may want to directly modify the resetting function to fit your own situation. Or you may choose to finish this TODO, test it and send me a pull request. Good luck.

**Comment by cykerway** [comment]
There is something new about this in version [1.14.0](https://github.com/cykerway/complete-alias/tree/1.14.0). In short, the script saves all current completions (except `-D` and `-F _complete_alias` ones) in an associative array variable on sourcing. This variable is queried later on when an alias command is being completed. This saves users the effort of manually specifying these "vanilla" completions. However, changes on those completions after the script is sourced are not caught. Users can re-source the script to refresh them.
