### ISSUE TITLE
Not working with `alias gitdiff="GIT_DIR= git diff"`

### ISSUE THREAD

**Issue by ackalker** [cykerway/complete-alias#14]
I'm trying to get complete-alias to work with the following alias (which lets me use the extended features of Git's `git diff` command on non-versioned files, outside of any repository):
```
alias gitdiff="GIT_DIR= git diff"
```
As completion setup, I use:
```
complete -F _complete_alias gitdiff
```

When I try the alias as follows, I don't get any completions:
```
$ gitdiff --<TAB>
```
I have setup Git completions, and the following gets me completions of its long options as expected:
```
$ GIT_DIR= git diff --<TAB>
```

**Comment by cykerway** [comment]
The problem is the word breaker doesn't know about redirections and variable assignments. I changed it a little bit to discard leading redirections and variable assignments. You can check the newest version here: https://github.com/cykerway/complete-alias/releases/tag/1.8.0 Your original example should just work with this version.

**Comment by cykerway** [comment]
The problem is the word breaker doesn't know about redirections and variable assignments. I changed it a little bit to discard leading redirections and variable assignments. You can check the newest version here: https://github.com/cykerway/complete-alias/releases/tag/1.8.0 Your original example should just work with this version.

**Comment by cykerway** [comment]
I'm testing with Bash 5.0 and it just works. If you are using a different version and still having problem then feel free to reopen.

**Comment by ackalker** [comment]
@cykerway Thanks for the fix, it works wonderfully.
