### ISSUE TITLE
Autoenabling completion for all aliases

### ISSUE THREAD

**Issue by lepotic** [cykerway/complete-alias#23]
Just an idea that you may want to add to the README or something. (Or not.)

Since I have a couple dozen aliases, I recently replaced all the
```bash
complete -F _complete_alias foo
complete -F _complete_alias bar
complete -F _complete_alias baz
...
```
with this in my `.bashrc`:
```bash
for a in ${!BASH_ALIASES[*]}; do
    complete -F _complete_alias $a
done
```
So far everything has been working like a charm.

And big thanks for this awesome script! It's a life saver.

**Comment by lepotic** [comment]
Oops, I guess I never read the whole README. You already have a similar advice. Closing.

**Comment by lepotic** [comment]
@cykerway re: a15dc15 - maybe using `${!BASH_ALIASES[*]}` like in the snippet above is better? No external commands and stdout parsing necessary.

**Comment by cykerway** [comment]
The manual says once `BASH_ALIASES` is unset then it loses its special properties. This might be why it wasn't used at the beginning. But now I guess this probably shouldn't matter because most users won't want to unset this variable or its elements. So let's use it in commit https://github.com/cykerway/complete-alias/commit/b16b183f6bf0029b9714b0e0178b6bd28eda52f3.
