### ISSUE TITLE
Borked on macOS

### ISSUE THREAD

**Issue by matthewadams** [cykerway/complete-alias#3]
This is borked due to differences in `sed` on macOS.  GNU `sed` uses `sed -r`, but macOS (BSD) uses `sed -e`.

```
matthew@newt:~
$ kubectl get
certificatesigningrequest  endpoints                  persistentvolume           rolebinding
clusterrolebinding         event                      persistentvolumeclaim      secret
componentstatus            horizontalpodautoscaler    pod                        service
configmap                  ingress                    poddisruptionbudget        serviceaccount
controllerrevision         job                        podsecuritypolicy          statefulset
cronjob                    namespace                  podtemplate                status
daemonset                  networkpolicy              replicaset                 storageclass
deployment                 node                       replicationcontroller
matthew@newt:~
$ kubectl get ^C
matthew@newt:~
$ k get sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
^C
matthew@newt:~
```

**Comment by dougpagani** [comment]
Minor correction: BSD `sed` does _not_ use `-e` for extended regexp. It uses `-E`.

`-e` for BSD-sed is for indicating another editing-command.

`-E` seems to be in the latest pull of GNU-sed, documented in its man-page, but not in a 2016 Ubuntu LTS, for example, that comes pre-packed with GNU's 2016 sed.

**Comment by dougpagani** [comment]
I tested `-E` on that 2016-`sed` which lacks the option in its _manual_.

However, even though it isn't in the manual, `-E` is an undocumented alternative 
for `-r`. See:
`echo 'dude' | sed -E 's/x|dude/foo/g'

... as an example on a machine to probe functionality in spite of what manual says.

**Comment by matthewadams** [comment]
...so using `-E` instead as of https://github.com/cykerway/complete-alias/pull/4/commits/bef2cb7186b2c0b2f5ceb3fc65ac1262505a2b76

**Comment by dougpagani** [comment]
Ah sorry, I missed the sub-line of "commit-fix." I saw "open" and didn't realize a fix was already submitted.

It may break for older versions of GNU-`sed`, but I have no idea really. It only became documented Feb '17 it looks like.

**Comment by matthewadams** [comment]
Ok, well, decide how you want to fix the issue & massage then merge when you're ready.  It's working for me, so thanks for publishing your repo!  :)

**Comment by cykerway** [comment]
Thanks for pointing out the problem. I think [GNU `sed`](https://www.gnu.org/software/sed/manual/sed.html) document should make it clear. [This thread](http://austingroupbugs.net/view.php?id=528) is also helpful in explaining `sed` portability issues. As a conclusion, using `sed -E` seems to be the best solution for this issue because it's POSIX standard.

However, please be aware that portability of this complete alias program may not be guaranteed at this time, because I don't really have a Mac at hand. Most of my development is done with GNU/Linux. I probably need volunteers for other operating systems. I'll add portability notice in README shortly.
