### ISSUE TITLE
Shell stops echoing typed characters after tab-completing (and exiting) blocking operations on remote machines

### ISSUE THREAD

**Issue by dsterda** [cykerway/complete-alias#5]
First of all, thank you for sharing this, I have used it for a while and it has been really helpful!

I noticed this issue recently; I wasn't able to figure out what was causing it by looking at the code, and I was wondering if you knew of a fix. Here is how to reproduce:

First, ssh into a remote machine (mine is on AWS).

Then create an alias for a command that blocks. My use case is `kubectl logs -f`, but `tail -f` will exhibit the same issue.

Then tab-complete the alias, press enter to run the command, and then CTRL+C to kill the streaming tail command.

Afterwards, the terminal does not show what I type, although it does go through (e.g. if I type `ls` and enter, it will list my directory). Running `reset` restores the shell properly.

Have you seen this behavior, and do you know of a potential fix? I found these posts which may or may not be helpful:

* [Shell does not show typed in commands, “reset” works, but what happened?](https://askubuntu.com/questions/171449/shell-does-not-show-typed-in-commands-reset-works-but-what-happened)
* [Fix terminal after displaying a binary file](https://unix.stackexchange.com/questions/79684/fix-terminal-after-displaying-a-binary-file)
* [Linux Terminal: typing feedback gone, line breaks not displayed
](https://stackoverflow.com/questions/17682934/linux-terminal-typing-feedback-gone-line-breaks-not-displayed)

Thank you!

**Comment by cykerway** [comment]
Hello,

Tested with `xterm` (332) and `bash` (4.4.12) but not able to reproduce. After I pressed `Ctrl-C` and typed `ls`, both the command and its output were displayed correctly.

If `reset` can fix your problem, then it's likely some terminal setting was changed when you ran the command. `complete-alias` is a shell alias completion program that doesn't change your terminal. You may want to double check your commands are aliased, and terminal configured properly. You may also want to upgrade your system to newest version and test with `xterm` and `bash` to see if it works properly. If problem still exists, you can post your system info, terminal and shell versions and config files so that I can try to reproduce. If problem fixed, please ack so that I can close this issue.

**Comment by dsterda** [comment]
Thank you for the detailed response, I appreciate it! I won't have a chance to check versions/config until next week, but I will follow up then. I'm glad to hear you aren't able to reproduce, hopefully it's just and issue on my end and I can figure it out :)

**Comment by dsterda** [comment]
The problem is persisting... I am currently running the following versions:

Laptop (OSX):
xterm: 7.6.0(324)
bash: 4.4.19(1) (not sure if that matters)

Remote (Ubuntu 16.04.4):
bash: 4.4.0(1)

Please let me know of other versions or config files I should post.

I cleared everything out of my .bashrc except for the alias, and that didn't fix it. I also don't observe the problem when tab completing `tail -f`, so it does seem to be related to the alias completion somehow.

Thanks!

**Comment by cykerway** [comment]
Hello, I upgraded my xterm and bash on both client and server to the newest version but still couldn't reproduce. Sorry I don't have a Mac at hand so I can't test on OSX. The README basically says support for non-Linux operating system is currently experimental. You may switch to a Linux client to see if the same problem still happens there.

**Comment by dsterda** [comment]
Ok, in that case it seems it's likely an issue with OSX. I don't have access to a Linux machine at the moment, but I'm assuming it would work based on your tests, so I can mark this as closed. I'll re-open if I ever get and chance to try on Linux and it doesn't work.
